# Generated by Django 4.2 on 2024-11-28 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="is_published",
        ),
    ]
