# Generated by Django 4.2 on 2024-11-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_remove_category_is_published"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="name",
            new_name="title",
        ),
    ]
